name: Infra_Pipeline

on: workflow_dispatch

permissions:
  contents: read
  id-token: write

env:
  WORK_DIR: Environments  

jobs:
  terraform_job:
    name: Terraform Job  
    runs-on: self-hosted
    environment: INFRA_UAT
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Terraform fmt
        id: fmt
        working-directory: ${{ env.WORK_DIR }}
        run: terraform fmt

      - name: Terraform Init
        id: init
        working-directory: ${{ env.WORK_DIR }}
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        working-directory: ${{ env.WORK_DIR }}
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.WORK_DIR }}
        run: terraform plan -no-color -input=false